## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the pollution_dataset.csv
import pandas as pd
pollution_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/23-Project-4-Week-1/resources/updated_pollution_dataset.csv")
pollution_df.shape

(5000, 10)

In [ ]:
# Determine the number of unique values in each column.
pollution_df.nunique()

Temperature                      362
Humidity                         723
PM2.5                            815
PM10                             955
NO2                              445
SO2                              348
CO                               265
Proximity_to_Industrial_Areas    179
Population_Density               683
Air Quality                        4
dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
# pollution_df = pd.get_dummies(pollution_df)
# pollution_df.head()

In [ ]:
# Split our preprocessed data into our features and target arrays
X = pollution_df.drop(columns='Air Quality').values
y = pd.get_dummies(pollution_df['Air Quality']).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [ ]:
X_test.shape

(1250, 9)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
nn_model = tf.keras.models.Sequential()

nn_model.add(tf.keras.layers.Dense(units=17, activation="relu", input_dim=9))

nn_model.add(tf.keras.layers.Dense(units=17, activation="relu"))

nn_model.add(tf.keras.layers.Dense(units=4, activation="softmax"))

nn_model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 17)                  │             170 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 17)                  │             306 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 4)                   │              72 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 548 (2.14 KB)

 Trainable params: 548 (2.14 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
118/118 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4516 - loss: 0.6353
Epoch 2/100
118/118 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6818 - loss: 0.3552
Epoch 3/100
118/118 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8273 - loss: 0.2395
Epoch 4/100
118/118 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8674 - loss: 0.1895
Epoch 5/100
118/118 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8846 - loss: 0.1579
Epoch 6/100
118/118 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8973 - loss: 0.1405
Epoch 7/100
118/118 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9064 - loss: 0.1308
Epoch 8/100
118/118 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9199 - loss: 0.1156
Epoch 9/100
118/118 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9266 - loss: 0.1046
Epoch 10/100
118/118 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9291 - loss: 0.1031
Epoch 11/100
118/118 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9346 - loss: 0.0941
Epoch 12/100
118/118 ━━━━━━━━━━━━━━━━━━━━

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

40/40 - 0s - 4ms/step - accuracy: 0.9448 - loss: 0.0703
Loss: 0.0702657550573349, Accuracy: 0.9448000192642212


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
# Convert predictions to discrete class labels using argmax
predictions = nn_model.predict(X_test_scaled) # Use scaled data for predictions
predicted_labels = predictions.argmax(axis=1)  # Get the index of the highest probability

# Convert y_test to a single-column format if it is one-hot encoded
y_test_labels = y_test.argmax(axis=1)  # Get the original class labels

# Create and save the testing classification report
testing_report = classification_report(y_test_labels, predicted_labels)

# Print the testing classification report
print(testing_report)

40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       508
           1       0.89      0.83      0.86       121
           2       0.94      0.97      0.95       376
           3       0.88      0.86      0.87       245

    accuracy                           0.94      1250
   macro avg       0.93      0.91      0.92      1250
weighted avg       0.94      0.94      0.94      1250



In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
testing_matrix = confusion_matrix(y_test_labels, predicted_labels)
print(testing_matrix)

[[507   0   1   0]
 [  0  98   0  23]
 [  0   0 366  10]
 [  0   8  15 222]]


In [ ]:
predictions

array([[1.36756242e-07, 1.09908838e-09, 9.99999344e-01, 5.10950827e-07],
       [9.99999940e-01, 3.82273442e-21, 8.23593277e-12, 8.22998916e-29],
       [6.00355143e-09, 9.80061054e-01, 2.25661330e-11, 1.99389998e-02],
       ...,
       [3.91897032e-07, 4.16335801e-08, 9.99896228e-01, 1.03213024e-04],
       [1.28387567e-08, 9.91064191e-01, 4.10619455e-11, 8.93586501e-03],
       [6.30222473e-07, 1.03461607e-05, 8.63283873e-01, 1.36705115e-01]],
      dtype=float32)

In [ ]:
y_test

Good  Hazardous  Moderate   Poor
2764  False      False      True  False
4767   True      False     False  False
3814  False       True     False  False
3499  False      False      True  False
2735  False      False     False   True
...     ...        ...       ...    ...
3015  False      False     False   True
1891  False      False     False   True
2773  False      False      True  False
3803  False       True     False  False
3301  False      False      True  False

[1250 rows x 4 columns]

## Save Results to HDF5 file

In [ ]:
# Export our model to HDF5 file
best_model.save('AirQuality_Assessment.keras')